# Generated by Django 2.0.13 on 2019-05-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=70)),
                ('publisher', models.CharField(max_length=70)),
                ('numberofplayersminimum', models.IntegerField()),
                ('numberofplayersmaximum', models.IntegerField()),
                ('age', models.IntegerField()),
                ('duration', models.DurationField()),
                ('type', models.CharField(max_length=200)),
                ('review', models.TextField(blank=True, null=True)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('skills', models.CharField(choices=[('CR', 'Concentratie'), ('GD', 'Geduld'), ('GH', 'Geheugen'), ('HR', 'Hoofdrekenen'), ('DR', 'Durf'), ('HK', 'Herkenning'), ('RV', 'Reactievermogen')], max_length=2)),
            ],
        ),
    ]
